# Generated by Django 5.1.1 on 2024-10-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('date_lost', models.DateField()),
                ('location_lost', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='lost_items/')),
            ],
        ),
    ]
