# Generated by Django 5.1.1 on 2024-10-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_founditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoundItem',
        ),
    ]
