# Generated by Django 5.1.1 on 2025-01-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_founditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=100)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('claimant_phone', models.CharField(max_length=15)),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('claim_message', models.TextField()),
                ('found_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.founditem')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.lostitem')),
            ],
        ),
    ]
