# Generated by Django 5.1.4 on 2025-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_itemtype_alter_founditem_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='item_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
